name: Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 25

      - uses: gradle/actions/setup-gradle@v6
        with:
          build-scan-publish: false
          cache-provider: basic
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

      - name: Run tests with JaCoCo (Gradle)
        run: ./gradlew test jacocoTestReport

      - name: Upload coverage report to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true

      - name: Upload JaCoCo HTML Report to GitHub Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v7
        with:
          name: jacoco-html-report
          path: build/reports/jacoco/test/html/
